import { classNameVariants, normalizePrefix } from "../core/names";
import { GlyphMeta } from "../types";

export const buildIconfontManifest = (params: {
  fontName: string;
  prefix: string;
  glyphs: GlyphMeta[];
}): string => {
  const { fontName, prefix, glyphs } = params;
  const cssPrefixText = normalizePrefix(prefix) || prefix;

  const manifest = {
    id: fontName,
    name: fontName,
    font_family: fontName,
    css_prefix_text: cssPrefixText,
    description: "Generated by svg2font-cli",
    glyphs: glyphs.map((glyph, index) => ({
      icon_id: `${glyph.name}-${index}`,
      name: glyph.name,
      font_class: glyph.name,
      unicode: glyph.codepoint.toString(16),
      unicode_decimal: glyph.codepoint,
      aliases: classNameVariants(prefix, glyph.name),
    })),
  };

  return JSON.stringify(manifest, null, 2);
};
